### ISSUE TITLE
 Ion Fury - "Aftershock" Support Planned?

### ISSUE THREAD

**Issue by gamer85** [emileb/Zeta_Touch#4]
Does anyone know if the new  Ion Fury - "Aftershock" will be supported on Zeta Touch android or if its being worked on?  I have purchased the new game on Steam and which to play on android.  Apologies if this is not the correct place to ask this question.

**Comment by emileb** [comment]
Yes I've added it and it's being tested now, full release very soon

**Comment by emileb** [comment]
Added. http://opentouchgaming.com/zeta-touch/
