### ISSUE TITLE
AMC Squad, SD Cards, and 3.2.1

### ISSUE THREAD

**Issue by anotherthing** [emileb/Zeta_Touch#5]
AMC Squad doesn't seem to work from the SD card in 3.2.1. If you look at the files settings, it shows every other game that Zeta Touch supports with the path where the files are located - with the exception of AMC Squad, so I'm thinking that might be the problem. 

Digging through the source, there doesn't seem to be a reference to AMC in the games list in RazeBaseLauncher.java, and in the AMC launcher code, it references RAZE_GAME_AWOL instead of AMC.

**Comment by emileb** [comment]
Hi, yes actually it is looking for a customised AMC build which is not thousands on individual files which takes ages to load on Android. Extract this to the AMC folder: AMCSquad_EP4_cache_v2.zip

**Comment by anotherthing** [comment]
You the man, Chief! I tried moving those hundreds of files in to the internal storage yesterday, and when that didn't work, deleting them. It took an hour and twenty minutes to delete all those files using X-plorer so I hear you about how long it does for Android to deal with all those files! Thanks for the speedy reply, on Christmas no less!
